name: Build e Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Login no Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagem Docker
        run: docker build -t ${{ github.DOCKER_REGISTRY }}/${{ github.DOCKER_REPOSITORY }}:${{ github.IMAGE_TAG }} .

      - name: Enviar imagem Docker
        run: docker push ${{ github.DOCKER_REGISTRY }}/${{ github.DOCKER_REPOSITORY }}:${{ github.IMAGE_TAG }}